window:
  padding:
    x: 1
    y: 1
  class:
    instance: Alacritty
    general: Alacritty
  startup_mode: Fullscreen
  # startup_mode: Maximized

font:
  size: 3

colors:
  primary:
    background: "#000000"
    foreground: "#ffffff"